
require 'optparse'
require 'yaml'
require 'nokogiri'
require 'open-uri'
require 'i18n'

require 'dictuby/string'
require 'dictuby/runner'
require 'dictuby/args_parser'
require 'dictuby/config'
require 'dictuby/online_dictionary'
require 'dictuby/sources/slovnik_sk'
require 'dictuby/sources/slovnik_cz'
require 'dictuby/sources/dict_cc'
